server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    server_tokens off;

    # Serve Angular app under /lmsui
    location /lmsui/ {
        try_files $uri $uri/ /lmsui/index.html;
    }
}

